name: Create Azure Storage Account for Backend Terraform State

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        region: [eastus2, centralus]
        environment: [connectivity, management]
    environment: ${{ matrix.environment }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Azure using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      # - name: login
      #   run: |
      #     echo "${{ secrets.AZURE_CREDENTIALS }}" > azure_creds.json
      #     az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      # - uses: azure/login@v2
      #   with:
      #     creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - run: |
          echo "Region: ${{ matrix.region }}"
          echo "Environment: ${{ substr(${{ matrix.environment }},1,4) }}"

      - name: Create Resource Group for Backend Storage
        run: |
          az group create --name rg-tf-backend-${{ matrix.environment }}-${{ matrix.region }}-001 --location ${{ matrix.region }}

      - name: Create Storage Account for Backend Storage
        run: |
          echo substr(${{ matrix.environment }},1,4)
          az storage account create --name sttf${{ matrix.environment }}${{ matrix.region }}001 --resource-group rg-tf-backend-${{ matrix.environment }}-${{ matrix.region }}-001 --location ${{ matrix.region }} --sku Standard_LRS

      - name: Create Blob Container for Backend Storage
        run: |
          az storage container create --name tfstate-${{ matrix.environment }}-${{ matrix.region }} --account-name sttf${{ matrix.environment }}${{ matrix.region }}001 #--auth-mode login

      # - name: Assign Storage Blob Data Contributor Role
      #   run: |
      #     az role assignment create --assignee  ${{ secrets.AZURE_CLIENT_ID }} --role "Storage Blob Data Contributor" --scope /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/rg-tf-backend-${{ matrix.environment }}-${{ matrix.region }}-001/providers/Microsoft.Storage/storageAccounts/sttf${{ matrix.environment }}${{ matrix.region }}001
