name: Azure Landing Zone for Connectivity - Terraform Unit Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read
  id-token: write


jobs:
  UnitTests:
    uses: ./.github/workflows/tflint.yml
    with:
      working_directory: ./connectivity 
    

  TerraformPlan:
    needs: UnitTests
    uses: ./.github/workflows/plan.yml    
    with:
      regions: '["eastus2","centralus"]'
      working_directory: ./connectivity
      environment: connectivity-build
      subscription: '["connectivity"]'    
    
    
    

#   TerraformApply:
#     needs: TerraformPlan
#     uses: ./.github/workflows/terraformapply.yml
#     with:
#       region: eastus2
#       environment: connectivity
#     secrets: inherit

      


    
        
