name: Azure Landing Zone for Connectivity - Terraform Unit Tests

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master

permissions:
  contents: read
  id-token: write


jobs:
  test:
    uses: ./.github/workflows/tflint.yml@master
    with:
      working_directory: ./connectivity
    


    
        
