name: Azure Landing Zone for Connectivity - Terraform Unit Tests

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master

permissions:
  contents: read
  id-token: write


jobs:
  terraform-unit-tests:
    name: Terraform Unit Tests
    runs-on: ubuntu-latest    
    steps:      
     - uses: ./workflows/tflint.yml
       with:
          working_directory: ./connectivity
        
