name: Provision Azure Landing Zone

on:
  push:
    branches:
      - main

jobs:
  call-deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: "prod"
      primary_region: "East US"
      secondary_region: "West US"
      subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
