name: Azure Landing Zone for Connectivity - Terraform Unit Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read
  id-token: write


jobs:
  TerraformUnitTests:
    name: Terraform Unit Tests
    uses: ./.github/workflows/tflint.yml
    with:
      working_directory: ./connectivity 
    

  TerraformPlan:
    needs: TerraformUnitTests
    uses: ./.github/workflows/plan.yml    
    with:
      regions: '["eastus2","centralus"]'
      working_directory: ./connectivity
      environment: connectivity-build
      subscription: '["connectivity"]'
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
  TerraformApply:
    needs: TerraformPlan
    uses: ./.github/workflows/apply.yml
    with:
      regions: '["eastus2","centralus"]'
      working_directory: ./connectivity
      environment: connectivity-deploy
      subscription: '["connectivity"]'
    secrets:      
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}

      


    
        
