name: Manual Approval Workflow

on:
  workflow_call:
   inputs:
      working_directory:
        type: string
        description: The working directory for the Terraform configuration files'
        required: true
        default: './connectivity'

permissions:
    contents: read
    id-token: write
    issues: write



jobs:    
  manual-approval:
    name: Manual Approval
    runs-on: ubuntu-latest    
    if: success() # Only proceed if terraform-plan job succeeds
    
    permissions:
      issues: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
      - name: Await Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: rengamurugesan@hotmail.com # Replace with GitHub usernames, with the free version you can only have an issue assigned to one username
          minimum-approvals: 1
          issue-title: "Manual Approval Required for Terraform Apply"
          issue-body: "Please approve or deny the deployment."
          fail-on-denial: true
