name: Test Azure login with OIDC

on:
  workflow_dispatch:
permissions:
  contents: read
  id-token: write

jobs:
  validate-azure-login:
    runs-on: self-hosted
    name: Validate Azure Login with OIDC
    environment: connectivity-build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Azure using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: rengamurugesan@hotmail.com
          minimum-approvals: 1
          issue-title: "test"
          issue-body: "Please approve or deny the deployment of version v1.3.5."
          exclude-workflow-initiator-as-approver: false
          fail-on-denial: true
          additional-approved-words: ''
          additional-denied-words: ''
