name: Terraform Paired-Region & Multi-Environment Plan (Azure)

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [eastus, westus]
        environment: [development, qa]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: login
        run: |
          echo "${{ secrets.AZURE_CREDENTIALS }}" > azure_creds.json
          az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        # with:
        #   terraform_version: 1.5.0

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Initialize Terraform
        run: terraform init

      - name: Select Workspace
        run: terraform workspace select ${{ matrix.environment }}-${{ matrix.region }} || terraform workspace new ${{ matrix.environment }}-${{ matrix.region }}

      - name: Terraform Plan
        run: terraform plan -var="location=${{ matrix.region }}" -var="environment=${{ matrix.environment }}" -out=tfplan-${{ matrix.environment }}-${{ matrix.region }}
