name: Azure Landing Zone for Connectivity

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  terraform-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        region: [eastus2, centralus]
        environment: [connectivity]
    environment: ${{ matrix.environment }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Azure using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      # - name: login
      #   run: |
      #     echo "${{ secrets.AZURE_CREDENTIALS }}" > azure_creds.json
      #     az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      # - uses: azure/login@v2
      #   with:
      #     creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - uses: bhowell2/github-substring-action@1.0.2
        id: env
        with:
          value: "${{ matrix.environment }}"
          length_from_start: 4

      - uses: bhowell2/github-substring-action@1.0.2
        id: region
        with:
          value: "${{ matrix.region }}"
          length_from_start: 6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        id: terraform-fmt
        run: terraform fmt -check
        working-directory: ./connectivity
        continue-on-error: true

      - name: Initialize Terraform
        id: terraform-init
        run: terraform init -reconfigure -input=false  -backend-config="storage_account_name=sttf${{ steps.env.outputs.substring }}${{ steps.region.outputs.substring }}001" -backend-config="resource_group_name=rg-tf-backend-${{ matrix.environment }}-${{ matrix.region }}-001" -backend-config="container_name=tfstate-${{ matrix.environment }}-${{ matrix.region }}" -backend-config="key=terraform.tfstate" #-backend-config="access_key=$(backendstoragekey)"
        working-directory: ./connectivity

      # - name: Select Workspace
      #   working-directory: ./connectivity
      #   run: |
      #     echo ${{ matrix.environment }}-${{ matrix.region }}
      #     #terraform workspace select ${{ Env.environment }}-${{ matrix.region }} -or-create
      #     terraform workspace list | grep "${{ matrix.environment }}-${{ matrix.region }}" || terraform workspace new ${{ matrix.environment }}-${{ matrix.region }}
      #     terraform workspace select ${{ matrix.environment }}-${{ matrix.region }}

      - name: Terraform Validate
        id: terraform-validate
        run: terraform validate -no-color
        working-directory: ./connectivity

      - name: Terraform Plan
        working-directory: ./connectivity
        run: |
          terraform plan -var="subscription_id="${{ secrets.SUBSCRIPTION_ID }}" -var="location=${{ matrix.region }}" -var="resource_group_name=rg-tf-${{ matrix.environment }}-${{ matrix.region }}-001" -out=tfplan-${{ matrix.environment }}-${{ matrix.region }}

      - name: Compress Artifact
        run: zip -r tfplan-${{ matrix.environment }}-${{ matrix.region }}.zip ./connectivity

      - name: Upload Terraform Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ matrix.environment }}-${{ matrix.region }}.zip
          path: ./*.zip
          retention-days: 2
          if-no-files-found: warn
          include-hidden-files: true

      - uses: actions/download-artifact@v4
        name: Download Terraform Plan Artifact
        with:
          name: tfplan-${{ matrix.environment }}-${{ matrix.region }}.zip
          run-id: ${{ github.event.workflow_run.id }}

      - name: Show Workflow Run ID
        run: |
          echo "Workflow Run ID: ${{ github.run_id }}"
