name: Terraform Paired-Region & Multi-Environment Plan (Azure)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [eastus, westus]
        environment: [development]
        include:
          - environment: development
            tenant_id: AZURE_TENANT_ID
            client_id_secret: AZURE_CLIENT_SECRET
            client_id: AZURE_CLIENT_ID
            subscription_id: AZURE_SUBSCRIPTION_ID
          # - environment: test
          #   client_id_secret: TEST_AZURE_CLIENT_ID
          #   client_secret_secret: TEST_AZURE_CLIENT_SECRET
          # - environment: prod
          #   client_id_secret: PROD_AZURE_CLIENT_ID
          #   client_secret_secret: PROD_AZURE_CLIENT_SECRET

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # - name: login
      #   run: |
      #     echo "${{ secrets.AZURE_CREDENTIALS }}" > azure_creds.json
      #     az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
          # client-id: "${{ secrets[matrix.client_id_secret] }}"
          # client-secret: "${{ secrets[matrix.client_secret_secret] }}"
          # tenant-id: "${{ secrets.AZURE_TENANT_ID }}"
          # subscription-id: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        # with:
        #   terraform_version: 1.5.0

      - name: Initialize Terraform
        run: terraform init

      - name: Select Workspace
        run: terraform workspace select ${{ matrix.environment }}-${{ matrix.region }} || terraform workspace new ${{ matrix.environment }}-${{ matrix.region }}

      - name: Terraform Plan
        run: terraform plan -var="location=${{ matrix.region }}" -var="environment=${{ matrix.environment }}" -out=tfplan-${{ matrix.environment }}-${{ matrix.region }}
