# File: .github/workflows/workflow.yml

on: [workflow_dispatch]

name: Run Azure Login With a Service Principal Secret

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: login
        run: |
          echo "${{ secrets.AZURE_CREDENTIALS }}" > azure_creds.json
          az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: terraform fmt
        run: terraform fmt -check
        working-directory: ./connectivity

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./connectivity

      - name: Terraform validate
        run: terraform validate
        working-directory: ./connectivity

      - name: Terraform plan
        run: terraform plan
        working-directory: ./connectivity

      # - name: "Terraform init"
      #   id: init
      #   run: |
      #     terraform init --backend-config="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" --backend-config="tenant_id=${{ secrets.AZURE_TENANT_ID }}" --backend-config="client_id=${{ secrets.AZURE_CLIENT_ID }}" --backend-config="client_secret=${{ secrets.AZURE_CLIENT_SECRET }}"
      #   env:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #     client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      # working-directory: "./connectivity"
