# File: .github/workflows/workflow.yml

on: [push]

name: Run Azure Login With a Service Principal Secret

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: login
        run: |
          echo "${{ secrets.AZURE_CREDENTIALS }}" > azure_creds.json
          az login --service-principal -u $(jq -r .clientId azure_creds.json) -p $(jq -r .clientSecret azure_creds.json) --tenant $(jq -r .tenantId azure_creds.json)
      # - uses: azure/login@v2
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
      #     auth-type: SERVICE_PRINCIPAL
      #     enable-AzPSSession: true
      #     # client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     # tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     #subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
