name: Terraform Paired-Region & Multi-Environment Plan (Azure)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        region: [eastus, westus]
        environment: [development, qa]
    environment: ${{ matrix.environment }} #development

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: login
        run: |
          echo "${{ secrets.AZURE_CREDENTIALS }}" > azure_creds.json
          az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: ./connectivity

      - name: Initialize Terraform
        run:
          terraform init -reconfigure  -backend-config="storage_account_name=sttf${{ matrix.environment }}${{ matrix.region }}001" -backend-config="resource_group_name=rg-tf-backend-${{ matrix.environment }}-${{ matrix.region }}-001" -backend-config="container_name=tfstate-${{ matrix.environment }}-${{ matrix.region }}" -backend-config="key=terraform.tfstate" #-backend-config="access_key=$(backendstoragekey)"
          #terraform init -reconfigure -backend-config="storage_account_name=$(StorageAccountName)"                                 -backend-config="resource_group_name=$(azureResourceGroup)"                                           -backend-config="container_name=$(ContainerName)"                                       -backend-config="key=$(key)" -backend-config="access_key=$(backendstoragekey)"
        working-directory: ./connectivity

      - name: Select Workspace
        working-directory: ./connectivity
        run: |
          echo ${{ matrix.environment }}-${{ matrix.region }}
          #terraform workspace select ${{ Env.environment }}-${{ matrix.region }} -or-create
          terraform workspace list | grep "${{ matrix.environment }}-${{ matrix.region }}" || terraform workspace new ${{ matrix.environment }}-${{ matrix.region }}
          terraform workspace select ${{ matrix.environment }}-${{ matrix.region }}

      # - name: Check State Lock
      #   run: terraform state list || echo "State file locked!"

      # - name: Force Unlock Terraform State
      #   run: |
      #     LOCK_ID=$(terraform force-unlock 2>&1 | grep -oE '[0-9a-fA-F-]{36}')
      #     echo "Lock ID: $LOCK_ID"
      #     terraform force-unlock $LOCK_ID

      - name: Terraform Plan
        working-directory: ./connectivity
        run: |
          ls -a
          cat provider.tf
          terraform plan  -var="location=${{ matrix.region }}" -var="resource_group_name=rg-tf-${{ matrix.environment }}-${{ matrix.region }}-001" -out=tfplan-${{ matrix.environment }}-${{ matrix.region }}
