name: Terraform Paired-Region & Multi-Environment Plan (Azure)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [eastus, westus]
        environment: [qa]
        include:
          - environment: qa
            tenant_id: AZURE_TENANT_ID
            client_id_secret: AZURE_CLIENT_SECRET
            client_id: AZURE_CLIENT_ID
            subscription_id: AZURE_SUBSCRIPTION_ID

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # - name: login
      #   run: |
      #     echo "${{ secrets.AZURE_CREDENTIALS }}" > azure_creds.json
      #     az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
      - name: test
        run: |
          if [ -z "{{ secrets[matrix.client_id_secret] }}" ]; then
            echo "client_id_secret is missing!"
            exit 1
          fi
          echo "client_id_secret is set."

          if [ -z "{{ secrets[matrix.subscription_id] }}" ]; then
            echo "subscription_id is missing!"
            exit 1
          fi
          echo "subscription_id is set."

          if [ -z "{{ secrets[matrix.client_id] }}" ]; then
            echo "client_id is missing!"
            exit 1
          fi
          echo "client_id is set."


          if [ -z "{{ secrets[matrix.tenant_id] }}" ]; then
            echo "tenant_id is missing!"
            exit 1
          fi
          echo "tenant_id is set."

        env:
          client-id: ${{ secrets[matrix.client_id] }}
          tenant-id: ${{ secrets[matrix.tenant_id] }}
          subscription-id: ${{ secrets[matrix.subscription_id] }}
          client_secret: ${{ secrets[matrix.client_id_secret] }}

      - uses: azure/login@v2
        # with:
        #   creds: '{"clientId":"{{ secrets[matrix.client_id] }}","clientSecret":"{{ secrets[matrix.client_id_secret] }}","subscriptionId":"{{ secrets[matrix.subscription_id] }}","tenantId":"{{ secrets[matrix.tenant_id] }}"}'
        #   auth-type: SERVICE_PRINCIPAL
        env:
          client-id: "${{ secrets[matrix.client_id] }}"
          tenant-id: ${{ secrets[matrix.tenant_id] }}
          subscription-id: ${{ secrets[matrix.subscription_id] }}
          client_secret: ${{ secrets[matrix.client_id_secret] }}
        # client-id: "${{ secrets[matrix.client_id_secret] }}"
        # client-secret: "${{ secrets[matrix.client_secret_secret] }}"
        # tenant-id: "${{ secrets.AZURE_TENANT_ID }}"
        # subscription-id: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        # with:
        #   terraform_version: 1.5.0

      - name: Initialize Terraform
        run: terraform init

      - name: Select Workspace
        run: terraform workspace select ${{ matrix.environment }}-${{ matrix.region }} || terraform workspace new ${{ matrix.environment }}-${{ matrix.region }}

      - name: Terraform Plan
        run: terraform plan -var="location=${{ matrix.region }}" -var="environment=${{ matrix.environment }}" -out=tfplan-${{ matrix.environment }}-${{ matrix.region }}
