    name: Test Runner Workflow

    on: [push]

    jobs:
      test_job:
        runs-on: self-hosted
        steps:
          - name: Run a command
            run: echo "Hello from my self-hosted scale set runner!"
            