name: Terraform Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install tflint
        run: go install github.com/terraform-linters/tflint/cmd/tflint@latest
      - name: Lint Terraform code
        run: tflint --format=json . > tflint.json
      - name: Check tflint output
        run: |
          if [[ ! -s tflint.json ]]; then
            echo "No tflint output"
            exit 0
          fi
          cat tflint.json
          if [[ $(cat tflint.json | jq -r 'length') -gt 0 ]]; then
            echo "Tflint errors found"
            exit 1
          fi
