name: Terraform Lint

on:
  push:
    branches: [main]
  workflow_dispatch:
  

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.52.0

      - name: Show version
        run: tflint --version
      
      - name: Init TFLint
        run: tflint --init
      
      - name: Run TFLint
        run: tflint -f compact

      - name: Lint Terraform code
        run: tflint --format=json . > tflint.json
        
      - name: Check tflint output
        run: |
          if [[ ! -s tflint.json ]]; then
            echo "No tflint output"
            exit 0
          fi
          cat tflint.json
          if [[ $(cat tflint.json | jq -r 'length') -gt 0 ]]; then
            echo "Tflint errors found"
            exit 1
          fi
