on:
  workflow_call:
    inputs:
      working_directory:
        type: string
        description: The working directory for the Terraform configuration files'
        required: true
        default: './connectivity'
jobs:
  terraform-unit-tests:
    name: Terraform Unit Tests
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        id: terraform-fmt
        run: terraform fmt -check
        working-directory: ${{ inputs.working_directory }}
        continue-on-error: true

      - name: Initialize Terraform
        id: terraform-init
        working-directory: ${{ inputs.working_directory }}
        run: |
          terraform init -reconfigure \
          -input=false  \
          -backend=false     
      - name: Terraform Validate
        id: terraform-validate
        run: terraform validate -no-color
        working-directory: ${{ inputs.working_directory }}
      
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.52.0

      - name: Show version
        run: tflint --version
      
      - name: Init TFLint
        working-directory: ${{ inputs.working_directory }}
        run: tflint --init
      
      - name: Run TFLint
        working-directory: ${{ inputs.working_directory }}
        run: tflint  --minimum-failure-severity warning -f compact
    
      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          tfsec_args: --soft-fail
          github_token: ${{ github.token }}
          tfsec_formats: sarif,csv
