name: Terraform state file creation

on:
  workflow_dispatch:
    inputs: 
      subscription:
        type: string
        description: The Azure subscription ID to use for the workflow
        required: true
        default: 'connectivity'
      environment:
        type: string
        description: The environment to use for the workflow
        required: true
        default: 'connectivity-build'
      regions:
        type: string
        description: The Azure regions to use for the workflow
        required: true
        default: '["eastus2","centralus"]' 

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        region: ${{ fromjson(inputs.regions) }}
        subscription: ${{ inputs.subscription }} 
    environment:  ${{ inputs.environment }}  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Azure using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
      - run: |
         echo ${{ inputs.subscription }} 
         echo ${{ matrix.region }}

      - uses: bhowell2/github-substring-action@1.0.2
        id: subscription
        with:
          value: ${{ inputs.subscription }} 
          length_from_start: 4

      - uses: bhowell2/github-substring-action@1.0.2
        id: region
        with:
          value: "${{ matrix.region }}"
          length_from_start: 6

      - name: Create Resource Group for Backend Storage
        run: |
          az group create --name rg-tf-backend-${{ matrix.subscriptions}}-${{ matrix.region }}-001 --location ${{ matrix.region }}

      - name: Create Storage Account for Backend Storage
        run: |

          az storage account create --name sttf${{ steps.subscription.outputs.substring }}${{ steps.region.outputs.substring }}001 --resource-group rg-tf-backend-${{ matrix.subscriptions}}-${{ matrix.region }}-001 --location ${{ matrix.region }} --sku Standard_LRS

      - name: Create Blob Container for Backend Storage
        run: |
          az storage container create --name tfstate-${{ matrix.subscriptions}}-${{ matrix.region }} --account-name sttf${{ steps.subscription.outputs.substring }}${{ steps.region.outputs.substring }}001 #--auth-mode login

      # - name: Assign Storage Blob Data Contributor Role
      #   run: |
      #     az role assignment create --assignee  ${{ secrets.AZURE_CLIENT_ID }} --role "Storage Blob Data Contributor" --scope /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/rg-tf-backend-${{ matrix.subscriptions}}-${{ matrix.region }}-001/providers/Microsoft.Storage/storageAccounts/sttf${{ matrix.subscriptions}}${{ matrix.region }}001
